[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  REACT_APP_API_URL = "https://salus-backend.onrender.com"
  NETLIFY_FORCE_BUILD = "true"
  BUILD_ID = "20250404143000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
